# Generated by Django 2.1.7 on 2019-04-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=10)),
                ('fp', models.FloatField()),
                ('bp', models.FloatField()),
                ('l', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lParent', to='bpapp.Node')),
                ('r', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rParent', to='bpapp.Node')),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='problem',
            name='root',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bpapp.Node'),
        ),
    ]
